### ISSUE TITLE
Fresh install BABEL issue

### ISSUE THREAD

**Issue by sean-hill** [apertureless/vue-chartjs#412]
### Expected Behavior

To run `npm run dev` with no compile issues.

### Actual Behavior

I am receiving this issue when running `npm run dev`:

```
$ npm run dev

> vue-chartjs@3.4.0 dev /vue-chartjs
> node build/dev-server.js

> Starting dev server...


 ERROR  Failed to compile with 1 errors                                                            11:40:23 AM

 error  in ./src/main.js

Module build failed: Error: [BABEL] /vue-chartjs/src/main.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/vue-chartjs/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/vue-chartjs/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/vue-chartjs/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/vue-chartjs/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/vue-chartjs/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/vue-chartjs/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/vue-chartjs/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/vue-chartjs/node_modules/@babel/core/lib/config/full.js:108:6)
    at transformSync (/vue-chartjs/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/vue-chartjs/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/vue-chartjs/node_modules/babel-loader/lib/index.js:55:20)
    at Object.module.exports (/vue-chartjs/node_modules/babel-loader/lib/index.js:179:20)

 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080
```

### Environment
- vue-chart.js version: 3.4.0
- npm version: 5.6.0

**Comment by BostonKenne** [comment]
@sean-hill  change your .babbel content to 
```
{
  "presets": [
    "@babel/preset-env"
  ]
}
```

and run 

> npx babel-upgrade --write --install
It work for me! hope it w'll help you.

**Comment by apertureless** [comment]
Yeah I need to upgrade the dependencies and clear the presets, if I find some time.
