### ISSUE TITLE
yarn install failed from source code

### ISSUE THREAD

**Issue by ekilzen** [apertureless/vue-chartjs#515]
### Expected Behavior
1. clone this repo
1. executed `yarn`
2. successfully installed all dependency.

### Actual Behavior
1. clone this repo
1. executed `yarn`
2. get following error:
```bash
vue-chartjs on  develop is 📦 v3.4.2 via ⬢ v10.15.3 took 7s
➜ yarn
yarn install v1.15.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
[1/6] ⢀ fsevents
[-/6] ⢀ waiting...
[3/6] ⢀ chromedriver
[-/6] ⢀ waiting...
error /Users/Like/work/vue-chartjs/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/Like/work/vue-chartjs/node_modules/chromedriver
Output:

```

### Environment
- vue.js version: <version here>
- vue-chart.js version: 3.4.2
- npm version: 6.9.0

### Other information
So after yarn install failed I using npm instead. The log is as following:
```bash
vue-chartjs on  develop is 📦 v3.4.2 via ⬢ v10.15.3 took 6s
➜ npm i
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> fsevents@1.2.9 install /Users/Like/work/vue-chartjs/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/Like/work/vue-chartjs/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> phantomjs-prebuilt@2.1.16 install /Users/Like/work/vue-chartjs/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/d3/v5yj2lxd0q56rk3mrsgpc27h0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/Like/work/vue-chartjs/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/d3/v5yj2lxd0q56rk3mrsgpc27h0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1557466904151/phantomjs-2.1.1-macosx -> /Users/Like/work/vue-chartjs/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/Like/work/vue-chartjs/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> chromedriver@2.46.0 install /Users/Like/work/vue-chartjs/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.46/chromedriver_mac64.zip
Saving to file: /var/folders/d3/v5yj2lxd0q56rk3mrsgpc27h0000gn/T/2.46/chromedriver/chromedriver_mac64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 4704K...
Received 5488K...
Received 6272K...
Received 6891K total.
Extracting zip contents
Copying to target path /Users/Like/work/vue-chartjs/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /Users/Like/work/vue-chartjs/node_modules/chromedriver/lib/chromedriver/chromedriver

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/Like/work/vue-chartjs/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @babel/preset-env@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/preset-stage-2@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-optional-catch-binding@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-unicode-property-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-optional-catch-binding@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-arrow-functions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-async-generator-functions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-async-generators@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-async-to-generator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-block-scoping@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-block-scoped-functions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-classes@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-computed-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-destructuring@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-dotall-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-duplicate-keys@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-exponentiation-operator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-for-of@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-function-name@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-literals@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-amd@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-commonjs@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-systemjs@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-umd@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-new-target@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-object-super@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-regenerator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-parameters@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-shorthand-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-sticky-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-template-literals@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-typeof-symbol@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-unicode-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN mini-css-extract-plugin@0.4.1 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN optimize-css-assets-webpack-plugin@4.0.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-serve@1.0.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-jsx@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-runtime@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-export-namespace-from@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-function-sent@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-decorators@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-numeric-separator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-throw-expressions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/preset-stage-3@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-async-generator-functions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-optional-catch-binding@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-unicode-property-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-async-generators@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-optional-catch-binding@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-decorators@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-export-namespace-from@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-function-sent@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-numeric-separator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-throw-expressions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-dynamic-import@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-import-meta@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @webpack-contrib/config-loader@1.2.1 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN koa-webpack@4.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.6.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN time-fix-plugin@2.0.5 requires a peer of webpack@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-hot-client@3.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

added 1915 packages from 1844 contributors and audited 22658 packages in 96.205s
found 39 vulnerabilities (15 low, 11 moderate, 12 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

It still failed on running dev server.

```bash
vue-chartjs on  develop [?] is 📦 v3.4.2 via ⬢ v10.15.3
➜ npm run dev

> vue-chartjs@3.4.2 dev /Users/Like/work/vue-chartjs
> node build/dev-server.js

> Starting dev server...


 ERROR  Failed to compile with 1 errors                                                                            13:59:39

 error  in ./src/main.js

Module build failed: Error: [BABEL] /Users/Like/work/vue-chartjs/src/main.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/Users/Like/work/vue-chartjs/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/Users/Like/work/vue-chartjs/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/config/full.js:108:6)
    at transformSync (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/transform.js:41:38)
    at Object.transform (/Users/Like/work/vue-chartjs/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/Users/Like/work/vue-chartjs/node_modules/babel-loader/lib/index.js:55:20)
    at Object.module.exports (/Users/Like/work/vue-chartjs/node_modules/babel-loader/lib/index.js:179:20)

 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080
```

**Comment by LesageKim** [comment]
I have the same problem. 

Downloaded the latest source code, 3.5.1
npm install
npm audit fix
npm install manually what was in npm audit

result:

`> Starting dev server...


 ERROR  Failed to compile with 1 errors                                                                                                                                                                                  10:03:38
 error  in ./src/main.js

Module build failed: Error: [BABEL] D:\Downloads\vue-chartjs-3.5.1\src\main.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "D:\\Downloads\\vue-chartjs-3.5.1\\node_modules\\@babel\\preset-stage-2\\lib\\index.js")
    at _default (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\preset-stage-2\lib\index.js:9:9)
    at D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\config\full.js:211:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (D:\Downloads\vue-chartjs-3.5.1\node_modules\gensync\index.js:251:28)
    at Function.sync (D:\Downloads\vue-chartjs-3.5.1\node_modules\gensync\index.js:89:14)
    at sync (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\gensync-utils\async.js:66:25)
    at sync (D:\Downloads\vue-chartjs-3.5.1\node_modules\gensync\index.js:182:19)
    at onFirstPause (D:\Downloads\vue-chartjs-3.5.1\node_modules\gensync\index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\config\caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPresetDescriptor (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\config\full.js:304:43)
    at loadPresetDescriptor.next (<anonymous>)
    at recursePresetDescriptors (D:\Downloads\vue-chartjs-3.5.1\node_modules\@babel\core\lib\config\full.js:112:30)

 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080`

What to do?
